/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\王晨冰\\Desktop\\vuePress\\node_modules\\_@vuepress_core@1.5.0@@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-094f9566",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-094f9566").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-5ebca95f",
    path: "/blog/css%E6%B5%AA%E6%BC%AB%E5%8A%A8%E7%94%BB/%E6%89%8B%E9%A3%8E%E7%90%B4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ebca95f").then(next)
    },
  },
  {
    path: "/blog/css浪漫动画/手风琴.html",
    redirect: "/blog/css%E6%B5%AA%E6%BC%AB%E5%8A%A8%E7%94%BB/%E6%89%8B%E9%A3%8E%E7%90%B4.html"
  },
  {
    name: "v-237ba684",
    path: "/blog/css%E6%B5%AA%E6%BC%AB%E5%8A%A8%E7%94%BB/loading%20%E5%8A%A0%E8%BD%BD%E5%8A%A8%E7%94%BB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-237ba684").then(next)
    },
  },
  {
    path: "/blog/css浪漫动画/loading 加载动画.html",
    redirect: "/blog/css%E6%B5%AA%E6%BC%AB%E5%8A%A8%E7%94%BB/loading%20%E5%8A%A0%E8%BD%BD%E5%8A%A8%E7%94%BB.html"
  },
  {
    name: "v-59400eb6",
    path: "/blog/css%E6%B5%AA%E6%BC%AB%E5%8A%A8%E7%94%BB/%E6%97%8B%E8%BD%AC%E6%9C%A8%E9%A9%AC.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59400eb6").then(next)
    },
  },
  {
    path: "/blog/css浪漫动画/旋转木马.html",
    redirect: "/blog/css%E6%B5%AA%E6%BC%AB%E5%8A%A8%E7%94%BB/%E6%97%8B%E8%BD%AC%E6%9C%A8%E9%A9%AC.html"
  },
  {
    name: "v-4e8fd4a3",
    path: "/blog/css%E6%B5%AA%E6%BC%AB%E5%8A%A8%E7%94%BB/%E9%9C%93%E8%99%B9%E7%81%AF%E5%85%AD%E8%A7%92%E5%BD%A2%E7%B2%92%E5%AD%90%E5%8A%A8%E7%94%BB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e8fd4a3").then(next)
    },
  },
  {
    path: "/blog/css浪漫动画/霓虹灯六角形粒子动画.html",
    redirect: "/blog/css%E6%B5%AA%E6%BC%AB%E5%8A%A8%E7%94%BB/%E9%9C%93%E8%99%B9%E7%81%AF%E5%85%AD%E8%A7%92%E5%BD%A2%E7%B2%92%E5%AD%90%E5%8A%A8%E7%94%BB.html"
  },
  {
    name: "v-e0352568",
    path: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/Cookie%E5%A2%9E%E5%88%A0%E6%94%B9%E6%9F%A5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e0352568").then(next)
    },
  },
  {
    path: "/blog/js封装工具/Cookie增删改查.html",
    redirect: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/Cookie%E5%A2%9E%E5%88%A0%E6%94%B9%E6%9F%A5.html"
  },
  {
    name: "v-f046b57a",
    path: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/Base64%E8%BD%ACBlob.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f046b57a").then(next)
    },
  },
  {
    path: "/blog/js封装工具/Base64转Blob.html",
    redirect: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/Base64%E8%BD%ACBlob.html"
  },
  {
    name: "v-e5247d42",
    path: "/blog/css%E6%B5%AA%E6%BC%AB%E5%8A%A8%E7%94%BB/%E9%9A%8F%E6%9C%BA%E8%BD%AE%E6%92%AD.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e5247d42").then(next)
    },
  },
  {
    path: "/blog/css浪漫动画/随机轮播.html",
    redirect: "/blog/css%E6%B5%AA%E6%BC%AB%E5%8A%A8%E7%94%BB/%E9%9A%8F%E6%9C%BA%E8%BD%AE%E6%92%AD.html"
  },
  {
    name: "v-f6549966",
    path: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/Number%E5%A4%84%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f6549966").then(next)
    },
  },
  {
    path: "/blog/js封装工具/Number处理.html",
    redirect: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/Number%E5%A4%84%E7%90%86.html"
  },
  {
    name: "v-15d7fe16",
    path: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E5%87%BD%E6%95%B0%E6%9F%AF%E9%87%8C%E5%8C%96.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15d7fe16").then(next)
    },
  },
  {
    path: "/blog/js封装工具/函数柯里化.html",
    redirect: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E5%87%BD%E6%95%B0%E6%9F%AF%E9%87%8C%E5%8C%96.html"
  },
  {
    name: "v-4f76e671",
    path: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E4%BF%9D%E7%95%99%E5%B0%8F%E6%95%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f76e671").then(next)
    },
  },
  {
    path: "/blog/js封装工具/保留小数.html",
    redirect: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E4%BF%9D%E7%95%99%E5%B0%8F%E6%95%B0.html"
  },
  {
    name: "v-0cf10732",
    path: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E5%B8%B8%E7%94%A8%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0cf10732").then(next)
    },
  },
  {
    path: "/blog/js封装工具/常用正则表达式.html",
    redirect: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E5%B8%B8%E7%94%A8%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F.html"
  },
  {
    name: "v-bc0606fc",
    path: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E6%8E%92%E5%BA%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bc0606fc").then(next)
    },
  },
  {
    path: "/blog/js封装工具/排序.html",
    redirect: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E6%8E%92%E5%BA%8F.html"
  },
  {
    name: "v-2b4caaa8",
    path: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E6%97%B6%E9%97%B4%E6%A0%BC%E5%BC%8F%E5%8C%96.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b4caaa8").then(next)
    },
  },
  {
    path: "/blog/js封装工具/时间格式化.html",
    redirect: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E6%97%B6%E9%97%B4%E6%A0%BC%E5%BC%8F%E5%8C%96.html"
  },
  {
    name: "v-b56311f2",
    path: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E8%8A%82%E6%B5%81&%E9%98%B2%E6%8A%96.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b56311f2").then(next)
    },
  },
  {
    path: "/blog/js封装工具/节流&防抖.html",
    redirect: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E8%8A%82%E6%B5%81&%E9%98%B2%E6%8A%96.html"
  },
  {
    name: "v-f99f0cb2",
    path: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%93%8D%E4%BD%9C.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f99f0cb2").then(next)
    },
  },
  {
    path: "/blog/js封装工具/滚动条操作.html",
    redirect: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%93%8D%E4%BD%9C.html"
  },
  {
    name: "v-9b73516e",
    path: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E8%BF%87%E6%BB%A4%E5%AF%B9%E8%B1%A1%E4%B8%AD%E4%B8%BA%E7%A9%BA%E7%9A%84%E5%B1%9E%E6%80%A7.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9b73516e").then(next)
    },
  },
  {
    path: "/blog/js封装工具/过滤对象中为空的属性.html",
    redirect: "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E8%BF%87%E6%BB%A4%E5%AF%B9%E8%B1%A1%E4%B8%AD%E4%B8%BA%E7%A9%BA%E7%9A%84%E5%B1%9E%E6%80%A7.html"
  },
  {
    name: "v-39ee13e8",
    path: "/docss/css%E6%A0%B7%E5%BC%8F/flex%E5%B8%83%E5%B1%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39ee13e8").then(next)
    },
  },
  {
    path: "/docss/css样式/flex布局.html",
    redirect: "/docss/css%E6%A0%B7%E5%BC%8F/flex%E5%B8%83%E5%B1%80.html"
  },
  {
    name: "v-fab951d8",
    path: "/docss/jsn/CentOS7%E5%AE%89%E8%A3%85Nginx.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fab951d8").then(next)
    },
  },
  {
    path: "/docss/jsn/CentOS7安装Nginx.html",
    redirect: "/docss/jsn/CentOS7%E5%AE%89%E8%A3%85Nginx.html"
  },
  {
    name: "v-7335e836",
    path: "/docss/jsn/DOM%E6%93%8D%E4%BD%9C.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7335e836").then(next)
    },
  },
  {
    path: "/docss/jsn/DOM操作.html",
    redirect: "/docss/jsn/DOM%E6%93%8D%E4%BD%9C.html"
  },
  {
    name: "v-98cbc88a",
    path: "/docss/jsn/TypeScript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-98cbc88a").then(next)
    },
  },
  {
    name: "v-6b28cd51",
    path: "/docss/jsn/BOM%E5%AF%B9%E8%B1%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6b28cd51").then(next)
    },
  },
  {
    path: "/docss/jsn/BOM对象.html",
    redirect: "/docss/jsn/BOM%E5%AF%B9%E8%B1%A1.html"
  },
  {
    name: "v-d806c88a",
    path: "/docss/jsn/Git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d806c88a").then(next)
    },
  },
  {
    name: "v-75fca7d1",
    path: "/docss/jsn/arguments%E5%AF%B9%E8%B1%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75fca7d1").then(next)
    },
  },
  {
    path: "/docss/jsn/arguments对象.html",
    redirect: "/docss/jsn/arguments%E5%AF%B9%E8%B1%A1.html"
  },
  {
    name: "v-713276db",
    path: "/docss/jsn/call%20&&%20apply%20&&%20bind.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-713276db").then(next)
    },
  },
  {
    path: "/docss/jsn/call && apply && bind.html",
    redirect: "/docss/jsn/call%20&&%20apply%20&&%20bind.html"
  },
  {
    name: "v-7a944102",
    path: "/docss/jsn/let,const,var%E5%8C%BA%E5%88%AB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a944102").then(next)
    },
  },
  {
    path: "/docss/jsn/let,const,var区别.html",
    redirect: "/docss/jsn/let,const,var%E5%8C%BA%E5%88%AB.html"
  },
  {
    name: "v-2365d3b2",
    path: "/docss/css%E6%A0%B7%E5%BC%8F/Grid%E5%B8%83%E5%B1%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2365d3b2").then(next)
    },
  },
  {
    path: "/docss/css样式/Grid布局.html",
    redirect: "/docss/css%E6%A0%B7%E5%BC%8F/Grid%E5%B8%83%E5%B1%80.html"
  },
  {
    name: "v-ba31053a",
    path: "/docss/jsn/%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BC%96%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ba31053a").then(next)
    },
  },
  {
    path: "/docss/jsn/函数式编程.html",
    redirect: "/docss/jsn/%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BC%96%E7%A8%8B.html"
  },
  {
    name: "v-69e2e17f",
    path: "/docss/jsn/%E6%9E%84%E9%80%A0%E5%87%BD%E6%95%B0%E4%B8%8E%E5%8E%9F%E5%9E%8B%E9%93%BE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69e2e17f").then(next)
    },
  },
  {
    path: "/docss/jsn/构造函数与原型链.html",
    redirect: "/docss/jsn/%E6%9E%84%E9%80%A0%E5%87%BD%E6%95%B0%E4%B8%8E%E5%8E%9F%E5%9E%8B%E9%93%BE.html"
  },
  {
    name: "v-0ef05ae7",
    path: "/docss/jsn/promise%E4%BD%BF%E7%94%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ef05ae7").then(next)
    },
  },
  {
    path: "/docss/jsn/promise使用.html",
    redirect: "/docss/jsn/promise%E4%BD%BF%E7%94%A8.html"
  },
  {
    name: "v-055cb7a6",
    path: "/docss/jsn/%E6%95%B0%E7%BB%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-055cb7a6").then(next)
    },
  },
  {
    path: "/docss/jsn/数组.html",
    redirect: "/docss/jsn/%E6%95%B0%E7%BB%84.html"
  },
  {
    name: "v-135bd5ec",
    path: "/docss/jsn/%E6%B7%B1%E6%8B%B7%E8%B4%9D%E4%B8%8E%E6%B5%85%E6%8B%B7%E8%B4%9D.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-135bd5ec").then(next)
    },
  },
  {
    path: "/docss/jsn/深拷贝与浅拷贝.html",
    redirect: "/docss/jsn/%E6%B7%B1%E6%8B%B7%E8%B4%9D%E4%B8%8E%E6%B5%85%E6%8B%B7%E8%B4%9D.html"
  },
  {
    name: "v-1092095f",
    path: "/docss/react/class%E7%B1%BB%E7%BB%84%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1092095f").then(next)
    },
  },
  {
    path: "/docss/react/class类组件.html",
    redirect: "/docss/react/class%E7%B1%BB%E7%BB%84%E4%BB%B6.html"
  },
  {
    name: "v-c18ea192",
    path: "/docss/jsn/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E8%B8%A9%E5%9D%91%E6%8C%87%E5%8D%97.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c18ea192").then(next)
    },
  },
  {
    path: "/docss/jsn/移动端踩坑指南.html",
    redirect: "/docss/jsn/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E8%B8%A9%E5%9D%91%E6%8C%87%E5%8D%97.html"
  },
  {
    name: "v-5fe158ce",
    path: "/docss/react/%E6%BA%90%E7%A0%81%E7%BC%96%E5%86%99.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5fe158ce").then(next)
    },
  },
  {
    path: "/docss/react/源码编写.html",
    redirect: "/docss/react/%E6%BA%90%E7%A0%81%E7%BC%96%E5%86%99.html"
  },
  {
    name: "v-4d770fca",
    path: "/docss/react/Hooks%E5%87%BD%E6%95%B0%E7%BB%84%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d770fca").then(next)
    },
  },
  {
    path: "/docss/react/Hooks函数组件.html",
    redirect: "/docss/react/Hooks%E5%87%BD%E6%95%B0%E7%BB%84%E4%BB%B6.html"
  },
  {
    name: "v-19e2275c",
    path: "/docss/react/%E5%85%AC%E7%94%A8%E5%86%85%E5%AE%B9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19e2275c").then(next)
    },
  },
  {
    path: "/docss/react/公用内容.html",
    redirect: "/docss/react/%E5%85%AC%E7%94%A8%E5%86%85%E5%AE%B9.html"
  },
  {
    name: "v-3561dbea",
    path: "/docss/webpacks/webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3561dbea").then(next)
    },
  },
  {
    name: "v-2871e136",
    path: "/docss/react/%E7%BB%84%E4%BB%B6antd%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2871e136").then(next)
    },
  },
  {
    path: "/docss/react/组件antd注意事项.html",
    redirect: "/docss/react/%E7%BB%84%E4%BB%B6antd%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9.html"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-ec38e77e",
    path: "/tag/Cookie/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-ec38e77e").then(next)
    },
    meta: {"pid":"tags","id":"Cookie"}
  },
  {
    path: "/tag/Cookie/index.html",
    redirect: "/tag/Cookie/"
  },
  {
    name: "v-e8d965c8",
    path: "/tag/JS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e8d965c8").then(next)
    },
    meta: {"pid":"tags","id":"JS"}
  },
  {
    path: "/tag/JS/index.html",
    redirect: "/tag/JS/"
  },
  {
    name: "v-0c1cbc56",
    path: "/tag/正则/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0c1cbc56").then(next)
    },
    meta: {"pid":"tags","id":"正则"}
  },
  {
    path: "/tag/正则/index.html",
    redirect: "/tag/正则/"
  },
  {
    path: "/tag/%E6%AD%A3%E5%88%99/",
    redirect: "/tag/正则/"
  },
  {
    name: "v-3259a754",
    path: "/tag/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3259a754").then(next)
    },
    meta: {"pid":"tags","id":"CSS"}
  },
  {
    path: "/tag/CSS/index.html",
    redirect: "/tag/CSS/"
  },
  {
    name: "v-d0fbe166",
    path: "/categories/Cookie/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-d0fbe166").then(next)
    },
    meta: {"pid":"categories","id":"Cookie"}
  },
  {
    path: "/categories/Cookie/index.html",
    redirect: "/categories/Cookie/"
  },
  {
    name: "v-d2055fbe",
    path: "/categories/前端小笔记/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-d2055fbe").then(next)
    },
    meta: {"pid":"categories","id":"前端小笔记"}
  },
  {
    path: "/categories/前端小笔记/index.html",
    redirect: "/categories/前端小笔记/"
  },
  {
    path: "/categories/%E5%89%8D%E7%AB%AF%E5%B0%8F%E7%AC%94%E8%AE%B0/",
    redirect: "/categories/前端小笔记/"
  },
  {
    name: "v-203633ba",
    path: "/categories/前端封装工具/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-203633ba").then(next)
    },
    meta: {"pid":"categories","id":"前端封装工具"}
  },
  {
    path: "/categories/前端封装工具/index.html",
    redirect: "/categories/前端封装工具/"
  },
  {
    path: "/categories/%E5%89%8D%E7%AB%AF%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/",
    redirect: "/categories/前端封装工具/"
  },
  {
    name: "v-75f01a3e",
    path: "/categories/正则/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-75f01a3e").then(next)
    },
    meta: {"pid":"categories","id":"正则"}
  },
  {
    path: "/categories/正则/index.html",
    redirect: "/categories/正则/"
  },
  {
    path: "/categories/%E6%AD%A3%E5%88%99/",
    redirect: "/categories/正则/"
  },
  {
    name: "v-85672be2",
    path: "/categories/排序/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-85672be2").then(next)
    },
    meta: {"pid":"categories","id":"排序"}
  },
  {
    path: "/categories/排序/index.html",
    redirect: "/categories/排序/"
  },
  {
    path: "/categories/%E6%8E%92%E5%BA%8F/",
    redirect: "/categories/排序/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]