/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "阿冰の神秘小屋",
  "description": "",
  "base": "/vuePress/",
  "headTags": [
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "script",
      {
        "src": "/vuePress/assets/js/bodyClick.js"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "阿冰の神秘小屋",
        "tagline": "一个被程序员生涯耽误的健体冠军",
        "heroTextStyle": {
          "color": "#fff"
        }
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-094f9566",
      "path": "/"
    },
    {
      "title": "旋转木马",
      "frontmatter": {
        "title": "旋转木马",
        "date": "2022-7-18"
      },
      "regularPath": "/blog/css%E6%B5%AA%E6%BC%AB%E5%8A%A8%E7%94%BB/%E6%97%8B%E8%BD%AC%E6%9C%A8%E9%A9%AC.html",
      "relativePath": "blog/css浪漫动画/旋转木马.md",
      "key": "v-59400eb6",
      "path": "/blog/css%E6%B5%AA%E6%BC%AB%E5%8A%A8%E7%94%BB/%E6%97%8B%E8%BD%AC%E6%9C%A8%E9%A9%AC.html"
    },
    {
      "title": "手风琴",
      "frontmatter": {
        "title": "手风琴",
        "date": "2022-7-18"
      },
      "regularPath": "/blog/css%E6%B5%AA%E6%BC%AB%E5%8A%A8%E7%94%BB/%E6%89%8B%E9%A3%8E%E7%90%B4.html",
      "relativePath": "blog/css浪漫动画/手风琴.md",
      "key": "v-5ebca95f",
      "path": "/blog/css%E6%B5%AA%E6%BC%AB%E5%8A%A8%E7%94%BB/%E6%89%8B%E9%A3%8E%E7%90%B4.html"
    },
    {
      "title": "Base64转blob对象",
      "frontmatter": {
        "title": "Base64转blob对象",
        "date": "2022-7-18",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/Base64%E8%BD%ACBlob.html",
      "relativePath": "blog/js封装工具/Base64转Blob.md",
      "key": "v-f046b57a",
      "path": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/Base64%E8%BD%ACBlob.html"
    },
    {
      "title": "call && apply && bind",
      "frontmatter": {
        "title": "call && apply && bind",
        "date": "2022-7-18",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/call%20&&%20apply%20&&%20bind.html",
      "relativePath": "blog/js封装工具/call && apply && bind.md",
      "key": "v-38a4feaf",
      "path": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/call%20&&%20apply%20&&%20bind.html"
    },
    {
      "title": "Number处理",
      "frontmatter": {
        "title": "Number处理",
        "date": "2022-7-18",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/Number%E5%A4%84%E7%90%86.html",
      "relativePath": "blog/js封装工具/Number处理.md",
      "key": "v-f6549966",
      "path": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/Number%E5%A4%84%E7%90%86.html",
      "headers": [
        {
          "level": 2,
          "title": "数字千分位分割",
          "slug": "数字千分位分割"
        },
        {
          "level": 2,
          "title": "生成随机数",
          "slug": "生成随机数"
        }
      ]
    },
    {
      "title": "Cookie",
      "frontmatter": {
        "title": "Cookie",
        "date": "2022-7-18",
        "subSidebar": false,
        "tags": [
          "Cookie"
        ],
        "categories": [
          "Cookie"
        ]
      },
      "regularPath": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/Cookie%E5%A2%9E%E5%88%A0%E6%94%B9%E6%9F%A5.html",
      "relativePath": "blog/js封装工具/Cookie增删改查.md",
      "key": "v-e0352568",
      "path": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/Cookie%E5%A2%9E%E5%88%A0%E6%94%B9%E6%9F%A5.html",
      "headers": [
        {
          "level": 2,
          "title": "增",
          "slug": "增"
        },
        {
          "level": 2,
          "title": "删",
          "slug": "删"
        },
        {
          "level": 2,
          "title": "查",
          "slug": "查"
        }
      ]
    },
    {
      "title": "保留小数",
      "frontmatter": {
        "title": "保留小数",
        "date": "2022-7-18",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E4%BF%9D%E7%95%99%E5%B0%8F%E6%95%B0.html",
      "relativePath": "blog/js封装工具/保留小数.md",
      "key": "v-4f76e671",
      "path": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E4%BF%9D%E7%95%99%E5%B0%8F%E6%95%B0.html"
    },
    {
      "title": "函数柯里化",
      "frontmatter": {
        "title": "函数柯里化",
        "date": "2022-7-18",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E5%87%BD%E6%95%B0%E6%9F%AF%E9%87%8C%E5%8C%96.html",
      "relativePath": "blog/js封装工具/函数柯里化.md",
      "key": "v-15d7fe16",
      "path": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E5%87%BD%E6%95%B0%E6%9F%AF%E9%87%8C%E5%8C%96.html"
    },
    {
      "title": "霓虹灯六角形粒子动画",
      "frontmatter": {
        "title": "霓虹灯六角形粒子动画",
        "date": "2022-7-18"
      },
      "regularPath": "/blog/css%E6%B5%AA%E6%BC%AB%E5%8A%A8%E7%94%BB/%E9%9C%93%E8%99%B9%E7%81%AF%E5%85%AD%E8%A7%92%E5%BD%A2%E7%B2%92%E5%AD%90%E5%8A%A8%E7%94%BB.html",
      "relativePath": "blog/css浪漫动画/霓虹灯六角形粒子动画.md",
      "key": "v-4e8fd4a3",
      "path": "/blog/css%E6%B5%AA%E6%BC%AB%E5%8A%A8%E7%94%BB/%E9%9C%93%E8%99%B9%E7%81%AF%E5%85%AD%E8%A7%92%E5%BD%A2%E7%B2%92%E5%AD%90%E5%8A%A8%E7%94%BB.html"
    },
    {
      "title": "常用正则表达式",
      "frontmatter": {
        "title": "常用正则表达式",
        "date": "2022-7-18",
        "tags": [
          "正则"
        ],
        "categories": [
          "正则"
        ]
      },
      "regularPath": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E5%B8%B8%E7%94%A8%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F.html",
      "relativePath": "blog/js封装工具/常用正则表达式.md",
      "key": "v-0cf10732",
      "path": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E5%B8%B8%E7%94%A8%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F.html",
      "headers": [
        {
          "level": 2,
          "title": "1.校验数字的表达式",
          "slug": "_1-校验数字的表达式"
        },
        {
          "level": 2,
          "title": "2.校验字符的表达式",
          "slug": "_2-校验字符的表达式"
        },
        {
          "level": 2,
          "title": "3.特殊需求表达式",
          "slug": "_3-特殊需求表达式"
        }
      ]
    },
    {
      "title": "排序",
      "frontmatter": {
        "title": "排序",
        "date": "2022-7-18",
        "tags": [
          "JS"
        ],
        "categories": [
          "排序"
        ]
      },
      "regularPath": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E6%8E%92%E5%BA%8F.html",
      "relativePath": "blog/js封装工具/排序.md",
      "key": "v-bc0606fc",
      "path": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E6%8E%92%E5%BA%8F.html",
      "headers": [
        {
          "level": 2,
          "title": "冒泡排序",
          "slug": "冒泡排序"
        },
        {
          "level": 2,
          "title": "插入排序",
          "slug": "插入排序"
        },
        {
          "level": 2,
          "title": "快速排序",
          "slug": "快速排序"
        },
        {
          "level": 2,
          "title": "选择排序",
          "slug": "选择排序"
        },
        {
          "level": 2,
          "title": "归并排序",
          "slug": "归并排序"
        },
        {
          "level": 2,
          "title": "计数排序",
          "slug": "计数排序"
        }
      ]
    },
    {
      "title": "滚动条操作",
      "frontmatter": {
        "title": "滚动条操作",
        "date": "2022-7-18",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%93%8D%E4%BD%9C.html",
      "relativePath": "blog/js封装工具/滚动条操作.md",
      "key": "v-f99f0cb2",
      "path": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%93%8D%E4%BD%9C.html"
    },
    {
      "title": "随机轮播",
      "frontmatter": {
        "title": "随机轮播",
        "date": "2022-7-18"
      },
      "regularPath": "/blog/css%E6%B5%AA%E6%BC%AB%E5%8A%A8%E7%94%BB/%E9%9A%8F%E6%9C%BA%E8%BD%AE%E6%92%AD.html",
      "relativePath": "blog/css浪漫动画/随机轮播.md",
      "key": "v-e5247d42",
      "path": "/blog/css%E6%B5%AA%E6%BC%AB%E5%8A%A8%E7%94%BB/%E9%9A%8F%E6%9C%BA%E8%BD%AE%E6%92%AD.html"
    },
    {
      "title": "时间格式化",
      "frontmatter": {
        "title": "时间格式化",
        "date": "2022-7-18",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E6%97%B6%E9%97%B4%E6%A0%BC%E5%BC%8F%E5%8C%96.html",
      "relativePath": "blog/js封装工具/时间格式化.md",
      "key": "v-2b4caaa8",
      "path": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E6%97%B6%E9%97%B4%E6%A0%BC%E5%BC%8F%E5%8C%96.html"
    },
    {
      "title": "节流&防抖",
      "frontmatter": {
        "title": "节流&防抖",
        "date": "2022-7-18",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E8%8A%82%E6%B5%81&%E9%98%B2%E6%8A%96.html",
      "relativePath": "blog/js封装工具/节流&防抖.md",
      "key": "v-b56311f2",
      "path": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E8%8A%82%E6%B5%81&%E9%98%B2%E6%8A%96.html",
      "headers": [
        {
          "level": 2,
          "title": "函数节流 throttle",
          "slug": "函数节流-throttle"
        },
        {
          "level": 2,
          "title": "函数防抖 debounce",
          "slug": "函数防抖-debounce"
        }
      ]
    },
    {
      "title": "过滤对象中为空的属性",
      "frontmatter": {
        "title": "过滤对象中为空的属性",
        "date": "2022-7-18",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E8%BF%87%E6%BB%A4%E5%AF%B9%E8%B1%A1%E4%B8%AD%E4%B8%BA%E7%A9%BA%E7%9A%84%E5%B1%9E%E6%80%A7.html",
      "relativePath": "blog/js封装工具/过滤对象中为空的属性.md",
      "key": "v-9b73516e",
      "path": "/blog/js%E5%B0%81%E8%A3%85%E5%B7%A5%E5%85%B7/%E8%BF%87%E6%BB%A4%E5%AF%B9%E8%B1%A1%E4%B8%AD%E4%B8%BA%E7%A9%BA%E7%9A%84%E5%B1%9E%E6%80%A7.html"
    },
    {
      "title": "BOM对象",
      "frontmatter": {
        "title": "BOM对象",
        "date": "2022-7-18"
      },
      "regularPath": "/docss/jsn/BOM%E5%AF%B9%E8%B1%A1.html",
      "relativePath": "docss/jsn/BOM对象.md",
      "key": "v-6b28cd51",
      "path": "/docss/jsn/BOM%E5%AF%B9%E8%B1%A1.html",
      "headers": [
        {
          "level": 2,
          "title": "判读浏览器是否支持 CSS 属性",
          "slug": "判读浏览器是否支持-css-属性"
        },
        {
          "level": 2,
          "title": "返回当前网页地址",
          "slug": "返回当前网页地址"
        },
        {
          "level": 2,
          "title": "获取滚动条位置",
          "slug": "获取滚动条位置"
        },
        {
          "level": 2,
          "title": "获取url中的参数",
          "slug": "获取url中的参数"
        },
        {
          "level": 2,
          "title": "页面跳转，是否记录在history中",
          "slug": "页面跳转，是否记录在history中"
        },
        {
          "level": 2,
          "title": "滚动条滚动到指定位置",
          "slug": "滚动条滚动到指定位置"
        },
        {
          "level": 2,
          "title": "复制文本",
          "slug": "复制文本"
        },
        {
          "level": 2,
          "title": "检测设备类型",
          "slug": "检测设备类型"
        }
      ]
    },
    {
      "title": "DOM操作",
      "frontmatter": {
        "title": "DOM操作",
        "date": "2022-7-18"
      },
      "regularPath": "/docss/jsn/DOM%E6%93%8D%E4%BD%9C.html",
      "relativePath": "docss/jsn/DOM操作.md",
      "key": "v-7335e836",
      "path": "/docss/jsn/DOM%E6%93%8D%E4%BD%9C.html",
      "headers": [
        {
          "level": 2,
          "title": "固定滚动条",
          "slug": "固定滚动条"
        },
        {
          "level": 2,
          "title": "判断当前位置是否为页面底部",
          "slug": "判断当前位置是否为页面底部"
        },
        {
          "level": 2,
          "title": "判断元素是否在可视范围内",
          "slug": "判断元素是否在可视范围内"
        },
        {
          "level": 2,
          "title": "获取元素css样式",
          "slug": "获取元素css样式"
        },
        {
          "level": 2,
          "title": "进入全屏",
          "slug": "进入全屏"
        },
        {
          "level": 2,
          "title": "退出全屏",
          "slug": "退出全屏"
        },
        {
          "level": 2,
          "title": "全屏事件",
          "slug": "全屏事件"
        }
      ]
    },
    {
      "title": "CentOS7安装Nginx",
      "frontmatter": {
        "title": "CentOS7安装Nginx",
        "date": "2022-7-18"
      },
      "regularPath": "/docss/jsn/CentOS7%E5%AE%89%E8%A3%85Nginx.html",
      "relativePath": "docss/jsn/CentOS7安装Nginx.md",
      "key": "v-fab951d8",
      "path": "/docss/jsn/CentOS7%E5%AE%89%E8%A3%85Nginx.html",
      "headers": [
        {
          "level": 2,
          "title": "1.下载Nginx安装包",
          "slug": "_1-下载nginx安装包"
        },
        {
          "level": 2,
          "title": "2.解压",
          "slug": "_2-解压"
        },
        {
          "level": 2,
          "title": "3.配置",
          "slug": "_3-配置"
        },
        {
          "level": 2,
          "title": "4.编译安装",
          "slug": "_4-编译安装"
        },
        {
          "level": 2,
          "title": "5.开机自动启动",
          "slug": "_5-开机自动启动"
        }
      ]
    },
    {
      "title": "Git",
      "frontmatter": {
        "title": "Git",
        "date": "2022-7-18"
      },
      "regularPath": "/docss/jsn/Git.html",
      "relativePath": "docss/jsn/Git.md",
      "key": "v-d806c88a",
      "path": "/docss/jsn/Git.html",
      "headers": [
        {
          "level": 2,
          "title": "常用命令",
          "slug": "常用命令"
        },
        {
          "level": 2,
          "title": "Git 相关",
          "slug": "git-相关"
        }
      ]
    },
    {
      "title": "flex布局",
      "frontmatter": {
        "title": "flex布局",
        "date": "2022-7-18"
      },
      "regularPath": "/docss/jsn/flex%E5%B8%83%E5%B1%80.html",
      "relativePath": "docss/jsn/flex布局.md",
      "key": "v-a0b4f49c",
      "path": "/docss/jsn/flex%E5%B8%83%E5%B1%80.html",
      "headers": [
        {
          "level": 2,
          "title": "live demo",
          "slug": "live-demo"
        },
        {
          "level": 2,
          "title": "属性解释",
          "slug": "属性解释"
        },
        {
          "level": 3,
          "title": "flexbox",
          "slug": "flexbox"
        },
        {
          "level": 3,
          "title": "flex-direction",
          "slug": "flex-direction"
        },
        {
          "level": 3,
          "title": "flex-wrap",
          "slug": "flex-wrap"
        },
        {
          "level": 3,
          "title": "flex-flow",
          "slug": "flex-flow"
        },
        {
          "level": 3,
          "title": "justify-content",
          "slug": "justify-content"
        },
        {
          "level": 3,
          "title": "align-items",
          "slug": "align-items"
        },
        {
          "level": 3,
          "title": "align-content",
          "slug": "align-content"
        },
        {
          "level": 3,
          "title": "order",
          "slug": "order"
        },
        {
          "level": 3,
          "title": "flex-basis",
          "slug": "flex-basis"
        },
        {
          "level": 3,
          "title": "flex-grow",
          "slug": "flex-grow"
        },
        {
          "level": 3,
          "title": "flex-shrink",
          "slug": "flex-shrink"
        },
        {
          "level": 3,
          "title": "align-self",
          "slug": "align-self"
        }
      ]
    },
    {
      "title": "loading 加载动画",
      "frontmatter": {
        "title": "loading 加载动画",
        "date": "2022-7-18"
      },
      "regularPath": "/docss/jsn/loading%20%E5%8A%A0%E8%BD%BD%E5%8A%A8%E7%94%BB.html",
      "relativePath": "docss/jsn/loading 加载动画.md",
      "key": "v-2ce03c74",
      "path": "/docss/jsn/loading%20%E5%8A%A0%E8%BD%BD%E5%8A%A8%E7%94%BB.html",
      "headers": [
        {
          "level": 2,
          "title": "loading_2",
          "slug": "loading-2"
        },
        {
          "level": 2,
          "title": "loading_3",
          "slug": "loading-3"
        },
        {
          "level": 2,
          "title": "loading_4",
          "slug": "loading-4"
        },
        {
          "level": 2,
          "title": "loading_5",
          "slug": "loading-5"
        },
        {
          "level": 2,
          "title": "loading_6",
          "slug": "loading-6"
        },
        {
          "level": 2,
          "title": "loading_7",
          "slug": "loading-7"
        },
        {
          "level": 2,
          "title": "相关项目",
          "slug": "相关项目"
        }
      ]
    },
    {
      "title": "移动端踩坑指南",
      "frontmatter": {
        "title": "移动端踩坑指南",
        "date": "2022-7-18"
      },
      "regularPath": "/docss/jsn/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E8%B8%A9%E5%9D%91%E6%8C%87%E5%8D%97.html",
      "relativePath": "docss/jsn/移动端踩坑指南.md",
      "key": "v-c18ea192",
      "path": "/docss/jsn/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E8%B8%A9%E5%9D%91%E6%8C%87%E5%8D%97.html",
      "headers": [
        {
          "level": 2,
          "title": "HTML方向",
          "slug": "html方向"
        },
        {
          "level": 3,
          "title": "调用系统功能",
          "slug": "调用系统功能"
        },
        {
          "level": 3,
          "title": "忽略自动识别",
          "slug": "忽略自动识别"
        },
        {
          "level": 3,
          "title": "弹出数字键盘",
          "slug": "弹出数字键盘"
        },
        {
          "level": 3,
          "title": "唤醒原生应用",
          "slug": "唤醒原生应用"
        },
        {
          "level": 3,
          "title": "禁止页面缩放",
          "slug": "禁止页面缩放"
        },
        {
          "level": 3,
          "title": "禁止页面缓存",
          "slug": "禁止页面缓存"
        },
        {
          "level": 3,
          "title": "禁止字母大写",
          "slug": "禁止字母大写"
        },
        {
          "level": 3,
          "title": "针对Safari配置",
          "slug": "针对safari配置"
        },
        {
          "level": 3,
          "title": "针对其他浏览器配置",
          "slug": "针对其他浏览器配置"
        },
        {
          "level": 3,
          "title": "让:active有效，让:hover无效",
          "slug": "让-active有效，让-hover无效"
        },
        {
          "level": 2,
          "title": "CSS方向",
          "slug": "css方向"
        },
        {
          "level": 3,
          "title": "自动适应布局",
          "slug": "自动适应布局"
        },
        {
          "level": 3,
          "title": "自动适应背景",
          "slug": "自动适应背景"
        },
        {
          "level": 3,
          "title": "监听屏幕旋转",
          "slug": "监听屏幕旋转"
        },
        {
          "level": 3,
          "title": "支持弹性滚动",
          "slug": "支持弹性滚动"
        },
        {
          "level": 3,
          "title": "禁止滚动传播",
          "slug": "禁止滚动传播"
        },
        {
          "level": 3,
          "title": "禁止屏幕抖动",
          "slug": "禁止屏幕抖动"
        },
        {
          "level": 3,
          "title": "禁止长按操作",
          "slug": "禁止长按操作"
        },
        {
          "level": 3,
          "title": "禁止字体调整",
          "slug": "禁止字体调整"
        },
        {
          "level": 3,
          "title": "禁止高亮显示",
          "slug": "禁止高亮显示"
        },
        {
          "level": 3,
          "title": "禁止动画闪屏",
          "slug": "禁止动画闪屏"
        },
        {
          "level": 3,
          "title": "美化表单外观",
          "slug": "美化表单外观"
        },
        {
          "level": 3,
          "title": "美化滚动占位",
          "slug": "美化滚动占位"
        },
        {
          "level": 3,
          "title": "美化输入占位",
          "slug": "美化输入占位"
        },
        {
          "level": 3,
          "title": "对齐输入占位",
          "slug": "对齐输入占位"
        },
        {
          "level": 3,
          "title": "对齐下拉选项",
          "slug": "对齐下拉选项"
        },
        {
          "level": 3,
          "title": "修复点击无效",
          "slug": "修复点击无效"
        },
        {
          "level": 3,
          "title": "识别文本换行",
          "slug": "识别文本换行"
        },
        {
          "level": 3,
          "title": "开启硬件加速",
          "slug": "开启硬件加速"
        },
        {
          "level": 3,
          "title": "描绘像素边框",
          "slug": "描绘像素边框"
        },
        {
          "level": 3,
          "title": "控制溢出文本",
          "slug": "控制溢出文本"
        },
        {
          "level": 2,
          "title": "JS方向",
          "slug": "js方向"
        },
        {
          "level": 3,
          "title": "禁止点击穿透",
          "slug": "禁止点击穿透"
        },
        {
          "level": 3,
          "title": "禁止滑动穿透",
          "slug": "禁止滑动穿透"
        },
        {
          "level": 3,
          "title": "支持往返刷新",
          "slug": "支持往返刷新"
        },
        {
          "level": 3,
          "title": "解析有效日期",
          "slug": "解析有效日期"
        },
        {
          "level": 3,
          "title": "修复输入监听",
          "slug": "修复输入监听"
        },
        {
          "level": 3,
          "title": "简化回到顶部",
          "slug": "简化回到顶部"
        },
        {
          "level": 3,
          "title": "简化懒性加载",
          "slug": "简化懒性加载"
        },
        {
          "level": 3,
          "title": "优化扫码识别",
          "slug": "优化扫码识别"
        },
        {
          "level": 3,
          "title": "自动播放媒体",
          "slug": "自动播放媒体"
        }
      ]
    },
    {
      "title": "数组方法",
      "frontmatter": {
        "title": "数组方法",
        "date": "2022-7-18"
      },
      "regularPath": "/docss/jsn/%E6%95%B0%E7%BB%84.html",
      "relativePath": "docss/jsn/数组.md",
      "key": "v-055cb7a6",
      "path": "/docss/jsn/%E6%95%B0%E7%BB%84.html",
      "headers": [
        {
          "level": 2,
          "title": "判断是不是数组",
          "slug": "判断是不是数组"
        },
        {
          "level": 2,
          "title": "Set()",
          "slug": "set"
        },
        {
          "level": 2,
          "title": "push()",
          "slug": "push"
        },
        {
          "level": 2,
          "title": "pop()",
          "slug": "pop"
        },
        {
          "level": 2,
          "title": "shift()",
          "slug": "shift"
        },
        {
          "level": 2,
          "title": "unshift()",
          "slug": "unshift"
        },
        {
          "level": 2,
          "title": "splice(i,n,x)",
          "slug": "splice-i-n-x"
        },
        {
          "level": 2,
          "title": "concat()",
          "slug": "concat"
        },
        {
          "level": 2,
          "title": "str.split()",
          "slug": "str-split"
        },
        {
          "level": 2,
          "title": "sort()",
          "slug": "sort"
        },
        {
          "level": 2,
          "title": "reverse()",
          "slug": "reverse"
        },
        {
          "level": 2,
          "title": "slice(start,end)",
          "slug": "slice-start-end"
        },
        {
          "level": 2,
          "title": "forEach((value,index,arr)=>{})",
          "slug": "foreach-value-index-arr"
        },
        {
          "level": 2,
          "title": "map((value,index,arr)=>{})",
          "slug": "map-value-index-arr"
        },
        {
          "level": 2,
          "title": "filter((value,index,arr)=>{})",
          "slug": "filter-value-index-arr"
        },
        {
          "level": 2,
          "title": "every((value,index,arr)=>{})",
          "slug": "every-value-index-arr"
        },
        {
          "level": 2,
          "title": "some()",
          "slug": "some"
        },
        {
          "level": 2,
          "title": "reduce((value,index,arr)=>{}, initialValue)",
          "slug": "reduce-value-index-arr-initialvalue"
        },
        {
          "level": 2,
          "title": "reduceRight((value,index,arr)=>{}, initialValue)",
          "slug": "reduceright-value-index-arr-initialvalue"
        },
        {
          "level": 2,
          "title": "indexOf(i,n)",
          "slug": "indexof-i-n"
        },
        {
          "level": 2,
          "title": "lastIndexOf()",
          "slug": "lastindexof"
        },
        {
          "level": 2,
          "title": "Array.from()",
          "slug": "array-from"
        },
        {
          "level": 2,
          "title": "Array.of()",
          "slug": "array-of"
        },
        {
          "level": 2,
          "title": "find((value,index,arr)=>{})",
          "slug": "find-value-index-arr"
        },
        {
          "level": 2,
          "title": "findIndex((value,index,arr)=>{})",
          "slug": "findindex-value-index-arr"
        },
        {
          "level": 2,
          "title": "arr.fill(target, start, end)",
          "slug": "arr-fill-target-start-end"
        },
        {
          "level": 2,
          "title": "includes(T,S)",
          "slug": "includes-t-s"
        },
        {
          "level": 2,
          "title": "entries()",
          "slug": "entries"
        },
        {
          "level": 2,
          "title": "arr.flat(Infinity) 数组拍平",
          "slug": "arr-flat-infinity-数组拍平"
        },
        {
          "level": 2,
          "title": "pop方法",
          "slug": "pop方法"
        },
        {
          "level": 2,
          "title": "unshift()方法",
          "slug": "unshift-方法"
        },
        {
          "level": 2,
          "title": "shift()",
          "slug": "shift-2"
        },
        {
          "level": 2,
          "title": "题目1",
          "slug": "题目1"
        },
        {
          "level": 2,
          "title": "题目2",
          "slug": "题目2"
        },
        {
          "level": 2,
          "title": "数组的方法清单",
          "slug": "数组的方法清单"
        },
        {
          "level": 2,
          "title": "数组的类型相关",
          "slug": "数组的类型相关"
        },
        {
          "level": 2,
          "title": "数组元素的添加和删除",
          "slug": "数组元素的添加和删除"
        },
        {
          "level": 2,
          "title": "数组的合并和拆分",
          "slug": "数组的合并和拆分"
        },
        {
          "level": 2,
          "title": "数组排序",
          "slug": "数组排序"
        },
        {
          "level": 2,
          "title": "查找数组的元素",
          "slug": "查找数组的元素"
        },
        {
          "level": 2,
          "title": "遍历数组",
          "slug": "遍历数组"
        }
      ]
    },
    {
      "title": "class类组件",
      "frontmatter": {
        "title": "class类组件",
        "date": "2022-07-14T00:00:00.000Z"
      },
      "regularPath": "/docss/react/class%E7%B1%BB%E7%BB%84%E4%BB%B6.html",
      "relativePath": "docss/react/class类组件.md",
      "key": "v-1092095f",
      "path": "/docss/react/class%E7%B1%BB%E7%BB%84%E4%BB%B6.html",
      "headers": [
        {
          "level": 2,
          "title": "setState//待更新",
          "slug": "setstate-待更新"
        },
        {
          "level": 2,
          "title": "类组件的传值方式",
          "slug": "类组件的传值方式"
        },
        {
          "level": 2,
          "title": "input数据存储",
          "slug": "input数据存储"
        },
        {
          "level": 2,
          "title": "React.memo",
          "slug": "react-memo"
        }
      ]
    },
    {
      "title": "Hooks函数组件",
      "frontmatter": {
        "title": "Hooks函数组件",
        "date": "2022-07-14T00:00:00.000Z"
      },
      "regularPath": "/docss/react/Hooks%E5%87%BD%E6%95%B0%E7%BB%84%E4%BB%B6.html",
      "relativePath": "docss/react/Hooks函数组件.md",
      "key": "v-4d770fca",
      "path": "/docss/react/Hooks%E5%87%BD%E6%95%B0%E7%BB%84%E4%BB%B6.html",
      "headers": [
        {
          "level": 2,
          "title": "hooks中父子组件的传值",
          "slug": "hooks中父子组件的传值"
        },
        {
          "level": 2,
          "title": "useState",
          "slug": "usestate"
        },
        {
          "level": 2,
          "title": "useEffect",
          "slug": "useeffect"
        },
        {
          "level": 2,
          "title": "useRef (createRef)",
          "slug": "useref-createref"
        },
        {
          "level": 2,
          "title": "useMemo 和 useCallback",
          "slug": "usememo-和-usecallback"
        },
        {
          "level": 2,
          "title": "useContext",
          "slug": "usecontext"
        },
        {
          "level": 2,
          "title": "useReducer",
          "slug": "usereducer"
        },
        {
          "level": 2,
          "title": "useReducer与useContext同时工作",
          "slug": "usereducer与usecontext同时工作"
        }
      ]
    },
    {
      "title": "公用内容",
      "frontmatter": {
        "title": "公用内容",
        "date": "2022-7-18"
      },
      "regularPath": "/docss/react/%E5%85%AC%E7%94%A8%E5%86%85%E5%AE%B9.html",
      "relativePath": "docss/react/公用内容.md",
      "key": "v-19e2275c",
      "path": "/docss/react/%E5%85%AC%E7%94%A8%E5%86%85%E5%AE%B9.html",
      "headers": [
        {
          "level": 2,
          "title": "react项目仓库初始化",
          "slug": "react项目仓库初始化"
        },
        {
          "level": 2,
          "title": "快速创建react项目",
          "slug": "快速创建react项目"
        },
        {
          "level": 2,
          "title": "React路由",
          "slug": "react路由"
        },
        {
          "level": 2,
          "title": "React生命周期",
          "slug": "react生命周期"
        },
        {
          "level": 2,
          "title": "Redux",
          "slug": "redux"
        },
        {
          "level": 2,
          "title": "消息订阅与发布",
          "slug": "消息订阅与发布"
        }
      ]
    },
    {
      "title": "源码编写",
      "frontmatter": {
        "title": "源码编写",
        "date": "2022-07-14T00:00:00.000Z"
      },
      "regularPath": "/docss/react/%E6%BA%90%E7%A0%81%E7%BC%96%E5%86%99.html",
      "relativePath": "docss/react/源码编写.md",
      "key": "v-5fe158ce",
      "path": "/docss/react/%E6%BA%90%E7%A0%81%E7%BC%96%E5%86%99.html",
      "headers": [
        {
          "level": 2,
          "title": "useState",
          "slug": "usestate"
        }
      ]
    },
    {
      "title": "组件antd注意事项",
      "frontmatter": {
        "title": "组件antd注意事项",
        "date": "2022-07-14T00:00:00.000Z"
      },
      "regularPath": "/docss/react/%E7%BB%84%E4%BB%B6antd%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9.html",
      "relativePath": "docss/react/组件antd注意事项.md",
      "key": "v-2871e136",
      "path": "/docss/react/%E7%BB%84%E4%BB%B6antd%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9.html",
      "headers": [
        {
          "level": 2,
          "title": "form表单获取和重置状态",
          "slug": "form表单获取和重置状态"
        },
        {
          "level": 2,
          "title": "Table表格",
          "slug": "table表格"
        },
        {
          "level": 2,
          "title": "Modal",
          "slug": "modal"
        },
        {
          "level": 2,
          "title": "ProComponents",
          "slug": "procomponents"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "JS Tags"
      },
      "regularPath": "/tag/JS/",
      "key": "v-e8d965c8",
      "path": "/tag/JS/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Cookie Tags"
      },
      "regularPath": "/tag/Cookie/",
      "key": "v-ec38e77e",
      "path": "/tag/Cookie/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "正则 Tags"
      },
      "regularPath": "/tag/%E6%AD%A3%E5%88%99/",
      "key": "v-0c1cbc56",
      "path": "/tag/正则/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端小笔记 Categories"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF%E5%B0%8F%E7%AC%94%E8%AE%B0/",
      "key": "v-d2055fbe",
      "path": "/categories/前端小笔记/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Cookie Categories"
      },
      "regularPath": "/categories/Cookie/",
      "key": "v-d0fbe166",
      "path": "/categories/Cookie/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "正则 Categories"
      },
      "regularPath": "/categories/%E6%AD%A3%E5%88%99/",
      "key": "v-75f01a3e",
      "path": "/categories/正则/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "排序 Categories"
      },
      "regularPath": "/categories/%E6%8E%92%E5%BA%8F/",
      "key": "v-85672be2",
      "path": "/categories/排序/"
    }
  ],
  "themeConfig": {
    "mode": "dark",
    "type": "blog",
    "search": true,
    "author": "阿冰",
    "authorAvatar": "/xiao.png",
    "nav": [
      {
        "text": "主页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "前端黑科技",
        "icon": "reco-date",
        "items": [
          {
            "text": "CSSの浪漫",
            "link": "/blog/css浪漫动画/手风琴"
          },
          {
            "text": "js封装工具",
            "link": "/blog/js封装工具/时间格式化"
          }
        ]
      },
      {
        "text": "牛逼の文章",
        "icon": "reco-document",
        "items": [
          {
            "text": "react",
            "link": "/docss/react/公用内容"
          },
          {
            "text": "js原生",
            "link": "/docss/jsn/数组"
          }
        ]
      },
      {
        "text": "码云",
        "icon": "reco-message",
        "items": [
          {
            "text": "gitee",
            "link": "https://gitee.com/wang-chenbing/dashboard/projects",
            "icon": "reco-github"
          }
        ]
      }
    ],
    "sidebar": {
      "/docss/react/": [
        {
          "title": "react",
          "collapsable": false,
          "children": [
            "公用内容",
            "class类组件",
            "Hooks函数组件",
            "源码编写",
            "组件antd注意事项"
          ]
        }
      ],
      "/docss/jsn/": [
        {
          "title": "js",
          "collapsable": false,
          "children": [
            "数组",
            "BOM对象",
            "DOM操作",
            "flex布局",
            "Git",
            "移动端踩坑指南",
            "CentOS7安装Nginx",
            "loading 加载动画"
          ]
        }
      ],
      "/blog/js封装工具/": [
        "时间格式化",
        "过滤对象中为空的属性",
        "Cookie增删改查",
        "函数柯里化",
        "滚动条操作",
        "排序",
        "call && apply && bind",
        "节流&防抖",
        "Base64转Blob",
        "保留小数",
        "常用正则表达式",
        "Number处理"
      ],
      "/blog/css浪漫动画/": [
        "手风琴",
        "随机轮播",
        "旋转木马",
        "霓虹灯六角形粒子动画"
      ]
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}