/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "JS": {
      "key": "JS",
      "scope": "tags",
      "path": "/tag/JS/",
      "pageKeys": [
        "v-67cd05f8",
        "v-2a30bac2",
        "v-04caf2e4",
        "v-0c21a8e6",
        "v-7d8c15ac",
        "v-5bb7cb77",
        "v-111ac246",
        "v-4f566ddc",
        "v-5f54743e",
        "v-3b5b1f88"
      ]
    },
    "Cookie": {
      "key": "Cookie",
      "scope": "tags",
      "path": "/tag/Cookie/",
      "pageKeys": [
        "v-2b41af7e"
      ]
    },
    "正则": {
      "key": "正则",
      "scope": "tags",
      "path": "/tag/正则/",
      "pageKeys": [
        "v-b25377c8"
      ]
    }
  },
  "categories": {
    "前端小笔记": {
      "key": "前端小笔记",
      "scope": "categories",
      "path": "/categories/前端小笔记/",
      "pageKeys": [
        "v-67cd05f8",
        "v-2a30bac2",
        "v-04caf2e4",
        "v-0c21a8e6",
        "v-7d8c15ac",
        "v-111ac246",
        "v-4f566ddc",
        "v-5f54743e",
        "v-3b5b1f88"
      ]
    },
    "Cookie": {
      "key": "Cookie",
      "scope": "categories",
      "path": "/categories/Cookie/",
      "pageKeys": [
        "v-2b41af7e"
      ]
    },
    "正则": {
      "key": "正则",
      "scope": "categories",
      "path": "/categories/正则/",
      "pageKeys": [
        "v-b25377c8"
      ]
    },
    "排序": {
      "key": "排序",
      "scope": "categories",
      "path": "/categories/排序/",
      "pageKeys": [
        "v-5bb7cb77"
      ]
    }
  },
  "timeline": {}
}