/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "JS": {
      "key": "JS",
      "scope": "tags",
      "path": "/tag/JS/",
      "pageKeys": [
        "v-f046b57a",
        "v-38a4feaf",
        "v-f6549966",
        "v-4f76e671",
        "v-15d7fe16",
        "v-bc0606fc",
        "v-f99f0cb2",
        "v-2b4caaa8",
        "v-b56311f2",
        "v-9b73516e"
      ]
    },
    "Cookie": {
      "key": "Cookie",
      "scope": "tags",
      "path": "/tag/Cookie/",
      "pageKeys": [
        "v-e0352568"
      ]
    },
    "正则": {
      "key": "正则",
      "scope": "tags",
      "path": "/tag/正则/",
      "pageKeys": [
        "v-0cf10732"
      ]
    }
  },
  "categories": {
    "前端小笔记": {
      "key": "前端小笔记",
      "scope": "categories",
      "path": "/categories/前端小笔记/",
      "pageKeys": [
        "v-f046b57a",
        "v-38a4feaf",
        "v-f6549966",
        "v-4f76e671",
        "v-15d7fe16",
        "v-f99f0cb2",
        "v-2b4caaa8",
        "v-b56311f2",
        "v-9b73516e"
      ]
    },
    "Cookie": {
      "key": "Cookie",
      "scope": "categories",
      "path": "/categories/Cookie/",
      "pageKeys": [
        "v-e0352568"
      ]
    },
    "正则": {
      "key": "正则",
      "scope": "categories",
      "path": "/categories/正则/",
      "pageKeys": [
        "v-0cf10732"
      ]
    },
    "排序": {
      "key": "排序",
      "scope": "categories",
      "path": "/categories/排序/",
      "pageKeys": [
        "v-bc0606fc"
      ]
    }
  },
  "timeline": {}
}